[package]
  name         = "baproto"
  version      = "0.1.4"
  description  = "An interface definition language (IDL) compiler for creating custom, bit-level binary encodings with an emphasis on supporting networked simulations."
  edition      = "2024"
  rust-version = "1.87.0"

[dependencies]
  anyhow         = "1.0.100"
  ariadne        = {version = "0.5.1", features = ["auto-color"]}
  chumsky        = {version = "0.12.0", features = ["lexical-numbers"]}
  clap           = {version = "4.5.42", features = ["cargo", "derive"]}
  derive_builder = "0.20.2"
  derive_more    = {version = "2.1.0", features = ["display"]}
  thiserror      = "2.0.12"

[dev-dependencies]
  rstest = {version = "0.26.1", default-features = false}
